### ISSUE TITLE
Neural network model throws an exception

### ISSUE THREAD

**Issue by tarek-nawara** [tarek-nawara/sentiment-analysis#43]
for some tweets the `neural network` model throw exceptions similar to the one here [issue](https://github.com/deeplearning4j/dl4j-examples/issues/587)

Our full log.
`
processing of request: 'Mis matched lengths: [16] != [28]'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.IllegalStateException: Mis matched lengths: [16] != [28]
       at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:40)
        at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:47)
        at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:24)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1267)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3753)
        at org.deeplearning4j.util.TimeSeriesUtils.reshape2dTo3d(TimeSeriesUtils.java:112)
        at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.output(RnnOutputLayer.java:142)
        at org.deeplearning4j.nn.layers.BaseOutputLayer.activate(BaseOutputLayer.java:189)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:789)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer
`

**Comment by MohamedElhawaty** [comment]
FIXED :sunglasses: :fire: :sunglasses:
